### ISSUE TITLE
Building requires git repo

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/iio-oscilloscope#109]
Users downloading the zip will get build failures since we directly reference git variables.

Here are some (might be others)
https://github.com/analogdevicesinc/iio-oscilloscope/blob/master/dialogs.c#L906
https://github.com/analogdevicesinc/iio-oscilloscope/blob/c37d0c2fa1e68dfdb301b4fef6cdc8974c91f102/dialogs.c#L946

**Comment by JanVerlinden** [comment]
The bug also exist if you use the Makefile or the CMakeLists.txt.

Building C object CMakeFiles/osc.dir/dialogs.c.o
/home/zynqdev/libiio-eclipse/osc-project/dialogs.c: In function ‘date_compare_against_build_date’:
/home/zynqdev/libiio-eclipse/osc-project/dialogs.c:906:21: error: too few arguments to function ‘atol’
  glong build_time = atol(GIT_COMMIT_TIMESTAMP);

**Comment by commodo** [comment]
Yep.
We're addressing both cases.
