### ISSUE TITLE
ini parsing seems weird

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#12]
As in the issue #11 - it looks like when running osc, it loads the ~/.osc_profile.ini, even if you give it a specific file with the -p option.

It should not do that.

-p means only load one file. the one that I point to.
if the file does not exist (-p foobar), it should not load any files, including not the default file

-Robin

**Comment by dNechita** [comment]
Fixed in commit https://github.com/analogdevicesinc/iio-oscilloscope/commit/1c42d07f769a6aeffa8b4fb04b2d59a181e217a1
