### ISSUE TITLE
Plugins fail to load on centos7 with xfs

### ISSUE THREAD

**Issue by reid-p** [analogdevicesinc/iio-oscilloscope#120]
in load_plugin_finish ent->d_type is return a value of 0 for all found plugins.

add this line to debug
fprintf(stderr, "lp %08x %s\n", ent->d_type, ent->d_name);

and get this as an example:
lp 00000000 fmcomms2.so
lp 00000000 fmcomms5.so
...

**Comment by commodo** [comment]
These mixes seem a bit rare/esoteric [XFS and/or d_type not being populated].

Typically, this would be a bug for XFS or glibc/uClibc/etc that you are using.
But I guess we can also handle this in a certain/generic manner.
