### ISSUE TITLE
Crashes on Windows

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/iio-oscilloscope#125]
With the latest OSC (v0.9) we have been seeing consistent crashes on Windows platforms when modifying parameters when scopes are running. Primarily the constellation scope.

Here are some repeatable steps that make OSC crash:
[IIO_Lab1.pdf](https://github.com/analogdevicesinc/iio-oscilloscope/files/2845867/IIO_Lab1.pdf)

This has been true for Win7 and Win10.

**Comment by mhennerich** [comment]
@adisuciu 
I know you fixed this. Are we ready to create a new release?

**Comment by mhennerich** [comment]
We have released a new version which should address these issues:
https://github.com/analogdevicesinc/iio-oscilloscope/releases/tag/v0.10-master

Please test and close

**Comment by tfcollins** [comment]
Seems to be working better now. Still need to sign exe release.
