### ISSUE TITLE
OSC crashes on boot with corrupted profile

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/iio-oscilloscope#127]
This happens a lot on Windows. A bad profile is created and auto-loaded when hardware is attached then OSC crashes without error or anything opening. Unplugging the hardware device and relaunching OSC fixes this or removing the profile file.

**Comment by rgetz** [comment]
I think this might be related to serial number and uri / usb processing - partial patch at #137

**Comment by dNechita** [comment]
@tfcollins is this stil happening? With the latest master I can't reproduce it.

**Comment by dNechita** [comment]
It is likely that this has been fixed during the partial patch mentioned above.
Closing this.
