### ISSUE TITLE
Unhandled tokens in ini file : Math.expanded & Math.active

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#13]
Unhandled tokens in ini file, 
Section IIO Oscilloscope - Capture Window3
Attribute : Math.expanded
Value: 0
Unhandled tokens in ini file, 
Section IIO Oscilloscope - Capture Window3
Attribute : Math.active
Value: 0

Even if we don't do anything with it - if we write it out, we should consume it without throwing a warning.

**Comment by dNechita** [comment]
Fix in commit https://github.com/analogdevicesinc/iio-oscilloscope/commit/e9fabcc43bb707a036ccbd8b232471c08acf3d18
