### ISSUE TITLE
Quit/Close in File Menu

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#14]
In the plot window, in the file menu, there is a "Quit".

This does not quit (it should), it just closes the window (there should be a new "Close").

While we are playing with this. CNTRL-Q should quit the application, no matter the window that is active, and CNTRL-W should close the active window. If the active window is the main one, then it should ask of you want to quit, ..

Make sense?

**Comment by dNechita** [comment]
Fix is in commits: https://github.com/analogdevicesinc/iio-oscilloscope/commit/7afeb4db4f26097cf7a11fa98a8c60a5e80a8069, https://github.com/analogdevicesinc/iio-oscilloscope/commit/30877e4d10ebb64acd3c736d44809fd723936ca7, https://github.com/analogdevicesinc/iio-oscilloscope/commit/04d9c54bfb0019a6f2c92e3748c9c62f92e90877
