### ISSUE TITLE
Make install problem when using cmake

### ISSUE THREAD

**Issue by nunojsa** [analogdevicesinc/iio-oscilloscope#155]
When using cmake, make install is falling. This is happening because `ldconfig` is not being executed after installation, leading to:
```
nsa@nsa-Precision-5530:~/work/iio-oscilloscope$ osc
osc: error while loading shared libraries: libosc.so.0: cannot open shared object file: No such file or directory 
```
So, I suggest we either make it happen during the install process or document it and say (hey, after make install you must run `sudo ldconfig`). Alternatively, we can use rpath/runpath...

**Comment by nunojsa** [comment]
This can be closed...

**Comment by JPHutchins** [comment]
I did not see this in the documentation here: https://wiki.analog.com/resources/tools-software/linux-software/libiio#how_to_build_it

Thanks for checking!
