### ISSUE TITLE
triggers in osc are broken

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#167]
They no longer work - I didn't go back to find out who broke this or when.

**Comment by mhennerich** [comment]
cannot reproduce - can you share your test settings?

**Comment by rgetz** [comment]
Sure - it looks like it is related to the number of samples...

(Digital loopback) 128 samples works:

![image](https://user-images.githubusercontent.com/1017869/61892231-4af1af00-aed9-11e9-87a5-d8b0b2f4d03e.png)

127 samples does not.
![image](https://user-images.githubusercontent.com/1017869/61892272-6a88d780-aed9-11e9-8e63-196f462066ef.png)

129 samples does not.
![image](https://user-images.githubusercontent.com/1017869/61892304-7d031100-aed9-11e9-86f4-2cc16ab97c14.png)

126 works
125 does not

looks like all odd sample numbers don't work (on Pluto).
