### ISSUE TITLE
AD9361 DDSes are broken

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#168]
You should be able to control the AD936x DSSes independently  - you no longer can. I think when the HDL updates were made to the DDS - something got broken.

Setup: On ADALM-PLUTO, set up digital loopback:
![image](https://user-images.githubusercontent.com/1017869/61845874-f9aed480-ae72-11e9-88f5-56884bba0d51.png)

Set the DDS to only be one signal on I, and nothing else:
![image](https://user-images.githubusercontent.com/1017869/61845942-3084ea80-ae73-11e9-9242-71c44fb502bd.png)

You still see two signals:
![image](https://user-images.githubusercontent.com/1017869/61845965-45fa1480-ae73-11e9-958b-2ee8ed119e0a.png)

This is a bug either in osc (the way it writes to the driver), in the driver (the way it writes to the HDL) or in the HDL itself.

**Comment by rgetz** [comment]
When things are 90 degrees out of phase, it works great:
![image](https://user-images.githubusercontent.com/1017869/61846129-f2d49180-ae73-11e9-8d72-951aae0e7848.png)
results in:
![image](https://user-images.githubusercontent.com/1017869/61846142-fec05380-ae73-11e9-8cbb-75dc35096a69.png)

changing to the same phase:
![image](https://user-images.githubusercontent.com/1017869/61846185-26afb700-ae74-11e9-83da-d6b6c38063b0.png)

doesn't change the output properly.
![image](https://user-images.githubusercontent.com/1017869/61846200-329b7900-ae74-11e9-9c36-837764543cf2.png)

**Comment by rgetz** [comment]
# iio_attr -C
IIO context with 7 attributes:
hw_model: Analog Devices PlutoSDR Rev.B (Z7010-AD9364)
hw_model_variant: 0
hw_serial: 104473222a87000618000600473ed57ae0
fw_version: v0.31
ad9361-phy,xo_correction: 40000000
ad9361-phy,model: ad9364
local,kernel: 4.14.0-42540-g387d584

osc is master

libiio is 

rgetz@brain:~/github/libiio/build$ iio_info 
Library version: 0.18 (git tag: c4833c5)
Compiled with backends: local xml ip usb serial

**Comment by mhennerich** [comment]
Hmm - what version of OSC are you using?
I can not reproduce this issue at all, using OSC from master, latest libiio and pluto-fw.

Also the triggering works for me.

**Comment by rgetz** [comment]
Doc is master from yesterday

**Comment by mhennerich** [comment]
I'm also using latest master builds. Could it be that your libiio is dirty? Can you try a fresh checkout?

**Comment by rgetz** [comment]
Looks like I accidentally set the Rx Rotation.

![image](https://user-images.githubusercontent.com/1017869/61883094-c64a6500-aec7-11e9-928e-2ab05370293b.png)

Yes - things are working as expected - sorry for the noise - I guess I shouldn't post bugs when it's late...
