### ISSUE TITLE
frequency domain wrong with FMCOMMS5

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#19]
![test](https://cloud.githubusercontent.com/assets/1017869/7254333/f33d8bde-e831-11e4-80a8-508915387d33.png)

For 30.720000 MSPS - the samples should be the same, and we should see -30 to +30 MHz, not -15 to + 45.

This just recently happened - I'm not sure when.

?

**Comment by dNechita** [comment]
I had this fix on another branch. It is now on the master branch as well: https://github.com/analogdevicesinc/iio-oscilloscope/commit/ff5f08d1158254c4cdf238ea3763555a006f873d
