### ISSUE TITLE
iio-oscilloscope not installing...

### ISSUE THREAD

**Issue by Joaozinho1** [analogdevicesinc/iio-oscilloscope#2]
Hi Everyone, I am newbie so please be patient with me.
I am trying to install the iio-osciloscope on the zedboard with FMCOMMS1-EBZ. it complained about libiio and other decencies, I did install alll dependecies except for the libiio. I downloaded teh sources and when I run make from the example folder this is what I get :
 cc -o ad9361-iiostream ad9361-iiostream.o  -liio
/usr/bin/ld: cannot find -liio
collect2: ld returned 1 exit status

can anyone help me, I have tried to google for solutions and I am getting nowhere.

**Comment by rgetz** [comment]
The IIO  Oscilloscope package, supports any IIO device, including the ones found on the AD-FMCOMMS1-EBZ.

detailed build instructions are at:
http://wiki.analog.com/resources/tools-software/linux-software/iio_oscilloscope

Let me know if you can't follow those.

-Robin
