### ISSUE TITLE
parsing ini files with non-fixed size incremental loops

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#21]
Today we support the ini parsing with the same syntax that the shell command supports.

NAME
       seq - print a sequence of numbers
SYNOPSIS
       seq [OPTION]... FIRST INCREMENT LAST

DESCRIPTION
       Print numbers from FIRST to LAST, in steps of INCREMENT.

It would be nice (like for the FMCOMMS1 test), were we test at different points, but they are not evenly spaced to handle a list, like the 

for i in {1 4 6 99 123}

can do

Some other keyword other than "SEQ" should be used.

may want to think about this while working on #20 .

-Robin

**Comment by dNechita** [comment]
Enhancement is at commit https://github.com/analogdevicesinc/iio-oscilloscope/commit/0a0818ea8c4ba0ae907abafb5a6472eece11bd25.

Usage:
\<FOR\> i in {1 4 6 99 123}
\</FOR\> 

You can also embed one or multiple \<FOR\> loops inside a \<SEQ\> loop or the other way around.
The space-separated values of the \<FOR\> loop can be any string(without spaces), not just integers. Something like this should work:

\<FOR\> message in {message1 message2 messge3}
test.message=\<message\>
\</FOR\>

-Dan

**Comment by rgetz** [comment]
This is great -- can we add some docs for this in the wiki?

Thanks

**Comment by dNechita** [comment]
Will do.

**Comment by rgetz** [comment]
Thanks - seems to be 
http://wiki.analog.com/resources/tools-software/linux-software/iio_oscilloscope_profile_guidelines

Tim : Can you update the FMCOMMS1 test for this? (to make it more readable?)

-Robin

**Comment by radhermit** [comment]
Sure, I can look at the FMCOMMS1 tests.

**Comment by radhermit** [comment]
I forgot to note, this has been in the fmcomms1-test branch for a while. I'd like to test it before merging but haven't gotten around to setting up the complete hardware configuration required for the tests yet.

**Comment by rgetz** [comment]
Since this is implemented - I will close this.
