### ISSUE TITLE
Enabling AD936x filters changes the Attenuation to a default value

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/iio-oscilloscope#247]

**Comment by mhennerich** [comment]
Sounds more like a driver bug - which was fixed some time ago.

https://github.com/analogdevicesinc/linux/commit/0c65bf6d1ae57a4675a7328fea8fc1c8edcbf87d#diff-d7708453ac00321b0a97234a6b0d47cf

**Comment by tfcollins** [comment]
Ill try with the latest firmware

**Comment by tfcollins** [comment]
Fix verified on Pluto. Closing.
