### ISSUE TITLE
CN05040 build fails

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/iio-oscilloscope#262]
C99 incompatible https://github.com/analogdevicesinc/iio-oscilloscope/blob/304cc0fbe55b9c5cab28c25b32332bd17afe5b63/plugins/cn0540.c#L175
and line 203.

This causes build failures on older Linaro builds.

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/iio-oscilloscope/commit/c5a79e56543a418c70b3751ee7390c548bbce767
