### ISSUE TITLE
Unable to detect context macOS 10.15

### ISSUE THREAD

**Issue by Scottpedia** [analogdevicesinc/iio-oscilloscope#269]
I cannot find a device via auto-selection when the pluto is plugged in. 
<img width="412" alt="Screen Shot 2020-09-08 at 13 47 50" src="https://user-images.githubusercontent.com/60531983/92510465-e4614a80-f1d9-11ea-9ca8-659c3742bc00.png">

**Comment by tfcollins** [comment]
If you are using --HEAD then you need to update libiio to use the newer auto-discovery features. Otherwise, install IIO-Scope without --HEAD or type in the context manually from iio_attr.

-Travis

**Comment by Scottpedia** [comment]
Thank you for your answer, I have already got it right.
