### ISSUE TITLE
Reading information from DMM tab whilst capturing data.

### ISSUE THREAD

**Issue by muaddib0308** [analogdevicesinc/iio-oscilloscope#29]
When I tried to read the temperature of the AD9361 (using the DMM tab) with my plot still capturing data, the tool crashed.

**Comment by rgetz** [comment]
This was on the windows version or the Linux version? I think I have done this on the Linux version without issue.

**Comment by muaddib0308** [comment]
Windows platform, thanks.

**Comment by pcercuei** [comment]
Are you using the alpha release released here: https://github.com/analogdevicesinc/iio-oscilloscope/releases/tag/v0.1-alpha1 ?

**Comment by muaddib0308** [comment]
Tim downloaded onto my machine last week, from Michael's share.  

(Analog Devices Inc. Industrial I/O Oscilloscope master-gb4a8aa3 helpful?)

Can download and re-assess

**Comment by muaddib0308** [comment]
Did not mean to close. 

Tim downloaded onto my machine, not sure from where... Michael's share?

(Analog Devices Inc. Industrial I/O Oscilloscope master-gb4a8aa3 helpful?)

Will download from your link and re-assess if needed.

**Comment by pcercuei** [comment]
I fixed some stability issues in the v0.1-alpha1 one. Nothing related to DMM though, so could you try to see if it indeed only happens when the DMM plugin refreshes?

**Comment by muaddib0308** [comment]
Downloaded from the link above and re-checked.  I do not see the error described any longer.

**Comment by pcercuei** [comment]
Ok, I'll close the issue then, please re-open if it happens again.
