### ISSUE TITLE
arm-none-eabi-gcc: error: unrecognized command line option '-pthread'

### ISSUE THREAD

**Issue by vladsolov** [analogdevicesinc/iio-oscilloscope#3]
Trying to compile this on pc with arm cross compiler ; 
Could u advice what to do about this error?

export CROSS_COMPILE=/usr/bin/arm-none-eabi-
root@elbit:/media/user/01CF9CA30F59CF20/SOC/catalina4CH/iio-oscilloscope-master/iio-oscilloscope-master# make
fatal: Not a git repository (or any parent up to mount point /media/user/01CF9CA30F59CF20)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /media/user/01CF9CA30F59CF20)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/usr/bin/arm-none-eabi-gcc -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/libdrm -I/usr/include/harfbuzz -I/usr/include/libxml2   -I/usr/include -fPIC -Wall -g -std=gnu90 -D_GNU_SOURCE -O2 -DPREFIX='"/usr/local"' -DOSC_VERSION=\"-g\"   -c -o oscmain.o oscmain.c
arm-none-eabi-gcc: error: unrecognized command line option '-pthread'
make: *** [oscmain.o] Error 1

**Comment by pcercuei** [comment]
Your toolchain cannot be used to compile Linux programs. You need a arm-linux-eabi toolchain.
