### ISSUE TITLE
Plot update

### ISSUE THREAD

**Issue by cuciureansergiu** [analogdevicesinc/iio-oscilloscope#303]
After changing the sampling frequency for an ADC, the FFT plot is showing the data based on the old sampling rate.
For example,  on a sinewave of 10khz:
default samping rate, reads 10khz
1/2 sampling rate, reads 20khz,
1/4 sampling rate, reads 40khz
Each time the sampling frequency is changed, osc has to be restarted (closing the plot window and opening another one won't fix this).

**Comment by mhennerich** [comment]
Where are you seeing this?
I think this is typically handled by the plugins.

**Comment by cuciureansergiu** [comment]
Here are some screenshots for a 5 khz sinewave and changing only the sampling frequency for the axi_adc:

![image](https://user-images.githubusercontent.com/16073026/104729161-b3bd8e80-5740-11eb-930d-946feffe3435.png)
![image](https://user-images.githubusercontent.com/16073026/104729200-c5069b00-5740-11eb-8897-4948852d2d4e.png)

After i restart osc

![image](https://user-images.githubusercontent.com/16073026/104729347-f97a5700-5740-11eb-8cb3-1e86f93dc914.png)

Seems like the graph data is stored once, when osc starts

**Comment by mhennerich** [comment]
Typically the plugin calls rx_update_device_sampling_freq(). In your case you use the DEBUG plugin and manipulate attributes.

**Comment by dNechita** [comment]
One idea is to have oscplot guess which attribute is for changing the sampling frequency (if plugin doesn't call rx_update_device_sampling_freq() or if there is no plugin). Then oscplot would read that attribute exactly when the start button gets clicked. This way, the sampling rate would get updated next time the capture is started which is better than having to restart the entire aplication.

**Comment by dbogdan** [comment]
Can't we check the sampling frequency each time the START button is pressed?

**Comment by dbogdan** [comment]
@dNechita , I was thinking the same. :)

**Comment by mhennerich** [comment]
I guess we do this already for computing the timeout in capture_setup()

**Comment by dNechita** [comment]
A fix for this has been made. Closing this issue.
