### ISSUE TITLE
master doesn't build on Zynq board

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#32]
I thinksome of the recent Makefile changes broke things.

This is *after* running the update_tools script.

root@analog:/usr/local/src/iio-oscilloscope# make
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
  CC      oscmain.o
oscmain.c:2:18: fatal error: glib.h: No such file or directory
 #include <glib.h>

**Comment by pcercuei** [comment]
Fixed in https://github.com/analogdevicesinc/linux_image_ADI-scripts/commit/571198cf5c7ef480b537fdddab30405d6dfd0b32
