### ISSUE TITLE
FMCOMMS5 doesn't calibrate if a cross correlation window is open (doesn't have to be running) 

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#35]
If I have a cross correlation window open, and active markers - the FMCOMMS5 calibration (in the advanced tab) seems to get all it's markers from it, (not the window the cal opens) and cal always fails.

Not sure if this is a problem with the actual cal, or the way that markers are brought from the capture windows.

-Robin

**Comment by dNechita** [comment]
There was a problem with how markers were brought from the capture window.
Fix is at: https://github.com/analogdevicesinc/iio-oscilloscope/commit/b24e0803288f80ae86ff494550360102d175c6fc

-Dan

**Comment by rgetz** [comment]
Thanks - I will check it out, and reopen if I see anything.
