### ISSUE TITLE
Missing documentation for 61_44_28MHz.ftr

### ISSUE THREAD

**Issue by cyber-g** [analogdevicesinc/iio-oscilloscope#390]
Hi, what is the design specifications of the [61_44_28MHz.ftr](https://github.com/analogdevicesinc/iio-oscilloscope/blob/master/filters/61_44_28MHz.ftr) filter configuration ? 

I could find some filter design specifications for the LTE cases (LTExx_MHz.ftr) here : https://wiki.analog.com/resources/eval/user-guides/ad-fmcomms2-ebz/software/filters#basic_functions

But the `61_44_28MHz.ftr` does not correspond to any communication standard...

May @dNechita give some explanation about the design parameters which where used in [MATLAB Filter Design Wizard for AD9361](https://wiki.analog.com/resources/eval/user-guides/ad-fmcomms2-ebz/software/filters) to produce this filter configuration ?

**Comment by tfcollins** [comment]
61_44_28MHz.ftr is simply a wideband filter used to maximize the RX bandwidth for use with the original design of the Spectrum Analyzer feature. It is not designed for any standard.
