### ISSUE TITLE
error: use of undeclared identifier 'M_PI'

### ISSUE THREAD

**Issue by yurivict** [analogdevicesinc/iio-oscilloscope#432]
```
/usr/ports/misc/iio-oscilloscope/work/iio-oscilloscope-0.16-master/oscplot.c:898:20: error: use of undeclared identifier 'M_PI'
                double a = 2.0 * M_PI / (n - 1);
                                 ^
/usr/ports/misc/iio-oscilloscope/work/iio-oscilloscope-0.16-master/oscplot.c:909:14: error: use of undeclared identifier 'M_PI'
                double a = M_PI * j / (n - 1);
                           ^
```

Removing ```-D_POSIX_C_SOURCE=200809L``` removes these errors.

Version: 0.16
clang-15
FreeBSD 13.2

**Comment by gastmaier** [comment]
M_PI is defined in the the [math.h header](https://www.man7.org/linux/man-pages/man0/math.h.0p.html), check if your system defines them somewhere like `/usr/include/math.h`, and if CMake is including the system headers properly.

**Comment by yurivict** [comment]
This looks like a system headers error.

Thank you for your help.

**Comment by dNechita** [comment]
Closing this, then.
