### ISSUE TITLE
ZCU102+FMCOMMS2 not detected by IIO Oscilloscope

### ISSUE THREAD

**Issue by danirojas037** [analogdevicesinc/iio-oscilloscope#438]
Hi,

I'm running a no-OS project with the following setup: ZCU102+FMCOMMS2, and trying to observe the spectrum of a received signal with an IIO Oscilloscope installed on a host (my desktop computer) and connected to the setup through serial connection, but the IIO Oscilloscope is not detecting the board:
![image](https://github.com/analogdevicesinc/iio-oscilloscope/assets/87932867/572dd339-f7df-48b1-8102-e880d8fefcac)

Any possible solution? 
(I've done a test with the PlutoSDR, and it is detected by the IIO Oscilloscope):
![image](https://github.com/analogdevicesinc/iio-oscilloscope/assets/87932867/4de127f3-ab4e-4f25-ba98-cf9371d27c1d)

Thanks,

Dani

**Comment by tfcollins** [comment]
Have you verified that the libiio context has started on the board itself and nothing else is blocking the UART interface?

**Comment by danirojas037** [comment]
> Have you verified that the libiio context has started on the board itself and nothing else is blocking the UART interface?
How can I verify that the libiio context has started on the board?

**Comment by danirojas037** [comment]
> Have you verified that the libiio context has started on the board itself and nothing else is blocking the UART interface?

How can I verify that the libiio context has started on the board?

**Comment by tfcollins** [comment]
UART on the board will provide feedback on boot that you can connect to the device over libiio. It should give you the required baudrate. What appears on your system at boot?

**Comment by Beauxrel** [comment]
Double check your .xdc file. I noticed that I had defined the wrong fmc port. Double check with you user guide on which is which

**Comment by danirojas037** [comment]
> 

I was able to solve it! 
The problem was that I haven't applied the configuration that appears on my system at boot:
![image](https://github.com/analogdevicesinc/iio-oscilloscope/assets/87932867/b1d2154c-ae1a-4bc1-982a-ef018c3aa78f)

When I applied this configuration to the IIO Oscilloscope, it detects the board:
![image](https://github.com/analogdevicesinc/iio-oscilloscope/assets/87932867/e2b3b343-58a6-4fcc-a11c-9d677904dd59)

Thanks for the help,

Dani
