### ISSUE TITLE
problem in capture

### ISSUE THREAD

**Issue by ali127124** [analogdevicesinc/iio-oscilloscope#443]
I want to connect the ADIS16465-1BMLZ module to the Raspberry Pi 4 using the EVAL-ADISIMU1-RPIZ board. To do this, I installed the Kuiper Linux operating system on the Raspberry Pi and ran the ADI IIO Oscilloscope software. Initially, nothing is displayed. By adding the following lines to the config.txt file as shown below, the data is displayed:

However, nothing is displayed in the plot section. What should I do?"

**Comment by nunojsa** [comment]
Hi,

> By adding the following lines to the config.txt file as shown below

Which line?

> However, nothing is displayed in the plot section. What should I do?"

Are you using FFT? Did you already tried to lower the fft size or the number of samples? Also, what channels are you trying to sample? We recently fixed a bug in libiio when you try to sample channels of different sizes. That will happen in your case if you mix temperature with the accel or gyro...

**Comment by ali127124** [comment]
![config](https://github.com/analogdevicesinc/iio-oscilloscope/assets/23422970/c23d9ed8-3c2e-47e1-b11f-bebe3a92f4e5)

**Comment by ali127124** [comment]
no i use real time
![msg85554708-130056](https://github.com/analogdevicesinc/iio-oscilloscope/assets/23422970/e62c134a-109f-4ac0-b44e-5a011acc3b95)
![msg85554708-130055](https://github.com/analogdevicesinc/iio-oscilloscope/assets/23422970/2916c703-d175-4361-a336-af0b94c81b23)
i have data in dmm but in plot nothing
![msg85554708-130055](https://github.com/analogdevicesinc/iio-oscilloscope/assets/23422970/11e2a0f2-9c5e-4357-bc2b-37fc39a48790)
![msg85554708-130056](https://github.com/analogdevicesinc/iio-oscilloscope/assets/23422970/9094fdc1-0988-42f4-b131-1907134b0df6)

**Comment by nunojsa** [comment]
Oh sure... You should not ignore messages " ... needs an impulse generator" :) 

The capture is not even enabled so there's no way to see a thing. You need to right click on the device in the plot channel and then look for the impluse generator setting. IIRC, you'll only have one option so there's no way to have it wrong. Let me know if it works...

**Comment by ali127124** [comment]
yes i saw the message but I don't know from which part it can be done, there is nothing in the settings part

**Comment by ali127124** [comment]
i right clicked on the device in the plot channel but nothing happened

**Comment by nunojsa** [comment]
> i right clicked on the device in the plot channel but nothing happened

Are you sure you're clicking on the right place?

![image](https://github.com/analogdevicesinc/iio-oscilloscope/assets/28741857/57023243-e246-486e-81d4-e2421e7fcba5)

In the above example, I  right click on top of axi-adrv9002-rx-lpc or in the rx2 device and I can see a pop up with "Trigger settings" and "Impulse generator settings". In my case, there's no impulse generator so I can't really click it.

**Comment by ali127124** [comment]
wow thaks so much yes it works

**Comment by ali127124** [comment]
can i save the data of the plot in .csv file?

**Comment by ali127124** [comment]
Is it possible to save information for a period of time, for example 5 minutes?

**Comment by ali127124** [comment]
> > i right clicked on the device in the plot channel but nothing happened
> 
> Are you sure you're clicking on the right place?
> 
> ![image](https://user-images.githubusercontent.com/28741857/258741410-57023243-e246-486e-81d4-e2421e7fcba5.png)
> 
> In the above example, I right click on top of axi-adrv9002-rx-lpc or in the rx2 device and I can see a pop up with "Trigger settings" and "Impulse generator settings". In my case, there's no impulse generator so I can't really click it.
wow thaks so much yes it works .Is it possible to save information for a period of time, for example 5 minutes?

**Comment by nunojsa** [comment]
> wow thaks so much yes it works .Is it possible to save information for a period of time, for example 5 minutes?

Not that I'm aware off. But maybe @dNechita can give you confirmation on that...

**Comment by ali127124** [comment]
> > wow thaks so much yes it works .Is it possible to save information for a period of time, for example 5 minutes?
> 
> Not that I'm aware off. But maybe @dNechita can give you confirmation on that...

thanks so much for your help

**Comment by tfcollins** [comment]
@ali127124  it isn't really possible to do a 5 minute capture. You would need to go to C or Python

**Comment by ali127124** [comment]
> @ali127124 it isn't really possible to do a 5 minute capture. You would need to go to C or Python

do you know any python library or python example code that I can use for my purpose?

**Comment by tfcollins** [comment]
@ali127124  sorry missed the last question. So you can use pylibiio directly or modify an existing IMU class for ADIS16465.
- pylibiio: http://analogdevicesinc.github.io/libiio/v0.25/python/index.html
- pyadi-iio IMU class example: https://github.com/analogdevicesinc/pyadi-iio/blob/master/adi/adis16460.py

**Comment by ali127124** [comment]
> @ali127124 sorry missed the last question. So you can use pylibiio directly or modify an existing IMU class for ADIS16465.
> 
> * pylibiio: http://analogdevicesinc.github.io/libiio/v0.25/python/index.html
> * pyadi-iio IMU class example: https://github.com/analogdevicesinc/pyadi-iio/blob/master/adi/adis16460.py

thanks much for getting back to me, my problem solved and I was forced to make a little change on pylibiio library(adis16495) in order to could connect to my sensor and got information from my sensor(adis16465)
anyway thanks for your help

**Comment by tfcollins** [comment]
Great! Looks like your issue is solved. I'll close the issue for now then.
