### ISSUE TITLE
running osc for a second time causes segfault ubuntu lunar lobster 23.04

### ISSUE THREAD

**Issue by chrisjohgorman** [analogdevicesinc/iio-oscilloscope#450]
I have installed iio-oscilloscope on a qemu machine loaded with ubuntu 23.04.  If I run osc once, I get a window and can connect to my device which is a pluto sdr.  If I run the oscilloscope a second time, I get a crash.

`$ cat .osc_crash_report 

IIO-Oscilloscope Crash Info

PID: 32580
Signal No: 11
Signal String: Segmentation fault
Error No: -12133
Error String: Unknown error -12133
Time Stamp: Sat Aug 26 11:52:46 2023

IIO-Oscilloscope Backtrace
osc(obtainBacktrace+0x5f)[0x560779de8ddf]
/lib/x86_64-linux-gnu/libc.so.6(+0x3c4b0)[0x7f944823c4b0]
/lib/x86_64-linux-gnu/libc.so.6(+0x17be2f)[0x7f944837be2f]
/lib/x86_64-linux-gnu/libiio.so.0(iio_channel_find_attr+0x4f)[0x7f944849f16f]
/lib/x86_64-linux-gnu/libiio.so.0(iio_channel_attr_write_raw+0x16)[0x7f944849f276]
/lib/x86_64-linux-gnu/libiio.so.0(iio_channel_attr_write_all+0xb3)[0x7f94484a00e3]
/usr/local/lib/libosc.so.0(update_from_ini+0xed)[0x7f94484810ed]
/usr/local/lib/osc//fmcomms2_adv.so(+0x69b1)[0x7f94401929b1]
/usr/local/lib/libosc.so.0(+0x1848b)[0x7f94484`

This can be circumvented by removing .osc_profile.ini before running the second time.  That is osc seems to fail when it parses .osc_profile.ini.

I have tried this out on the host machine as well, which is a arch linux machine.  The results are the same.

**Comment by cristina-suteu** [comment]
Hello, 
This is likely a libiio issue. We are looking into a fix for this. 
In the mean time, if you would like to be able to load Pluto profiles , we suggest using v0.24 of libiio. 
To do this, you need to rebuild libiio : 
cd libiio
git checkout v0.24 
cd build 
cmake ../
make 
sudo make install

Please make sure that you have deleted the previously generated v0.25 objects from the install location, to ensure that IIO-Oscilloscope links to the correct libiio.
