### ISSUE TITLE
OSC cannot handle multiple instances of the same chip (should use label instead of name)

### ISSUE THREAD

**Issue by MikeLooijmans** [analogdevicesinc/iio-oscilloscope#480]
The "name" of an iio device is the chip name, and usually isn't unique.
The DMM window correctly shows and uses labels.
The OSC plot view doesn't and gets hopelessly confused. With multiple instances of chipX, the plot window will not show this:

- chipX
- channel0
- channel1
- chipX
- channel0
- channel1

Instead the list is shown as:

- chipX
- channel0
- channel1
- channel0
- channel1
- chipX

**Comment by dNechita** [comment]
Hi!
Thanks for reporting this! We will look into this.
