### ISSUE TITLE
runRemote

### ISSUE THREAD

**Issue by vladsolov** [analogdevicesinc/iio-oscilloscope#5]
Thnaks for the previous fast responses! Very impressive support!!!
I am sorry if the next question is the absent of my understanding ; 
It is said on the wiki page that the osc app can be run remotely, is it mean i can run linaro with osc on my host and get the data from the card on the target? what must be installed on the target to make it pass data to the host?
Thanks a lot...

Running Remote
=============
The application can be used to connect to another platform that has a connected device in order to configure the device and  !!!! read data from it  !!!! .

**Comment by pcercuei** [comment]
Settings -> Connect
Then just enter the IP address of the target and click OK.

**Comment by vladsolov** [comment]
ok, but what do i need to run on the target? must i run linaro desktop or maybe linaro nano or may i use any other os? must i install osc with gui and x11 on the target?

**Comment by pcercuei** [comment]
You need https://github.com/analogdevicesinc/libiio installed on the target (both the library and the iiod server).
We only support our linaro image, although it should work as well with other distributions.

**Comment by vladsolov** [comment]
Thanks for the response; i got the library and the iiod installed on the targer;
Could u pls advice on how to make the iiod pass data to osc on other machine?
thanks;

**Comment by pcercuei** [comment]
On the target, you need a kernel with IIO support.
Please don't use bug reports to ask for help; use https://ez.analog.com instead.
