### ISSUE TITLE
Addition of qpsk waveforms breaks installer

### ISSUE THREAD

**Issue by EmbeddedGroup** [analogdevicesinc/iio-oscilloscope#51]
This commit breaks the installer. The makefile is not set up to copy the "qpsk" subdirectory and stops when trying to copy/install the "waveforms" directory.

**Comment by rgetz** [comment]
Assume you are talking about 141c8545c7b59260c67aace37c2f060595307d00?

Assigning to dan.

**Comment by dNechita** [comment]
Fixed with commit: https://github.com/analogdevicesinc/iio-oscilloscope/commit/ebf7650bb20df4be1b015ec7c0880868238339f4

Thank you!

**Comment by radhermit** [comment]
Closing since I assume this is fixed as described in the previous comment.
