### ISSUE TITLE
Connect dialog label incorrectly labeled ip:port

### ISSUE THREAD

**Issue by cdleonard** [analogdevicesinc/iio-oscilloscope#52]
I tried to do port forwarding from 127.0.0.1:3322 to iiod running on a different host (inside qemu). Attempting to connect to 127.0.0.1:3322 apparently does not work. The entire string is interpreted as a hostname and DNS resolution obviously fails. As far as I can tell the port number is actually hardcoded throughout the entire libiio stack.

The GUI label should read something like "hostname" instead.

**Comment by rgetz** [comment]
I think this has been resolved - but Paul should comment for sure.

**Comment by pcercuei** [comment]
I don't think it's been resolved. Let me fix that quickly.
