### ISSUE TITLE
test failures don't return error codes

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#54]
It use to be when a profile/test was run, and the test failed, the OSC application returned a non-success error code, so that shell scripts would understand what was going on.

This is no longer the case, and causes issues in the test infrastructure.

I don't know who wants to have a look at things (or who has time?)

Thanks
-Robin

**Comment by radhermit** [comment]
I've had a patch sitting around for doing vibration tests fully on the command line running osc under Xvfb that probably handles this fix among other things (https://github.com/analogdevicesinc/board-tests/blob/master/picozed-sdr1-brk/vibration/osc-cli-test.patch).

In particular, the return codes from the profile loading part of the patch should fix this. I'll clean it up and push the relevant changes.

**Comment by rgetz** [comment]
Yeah - that looks like it should fix things up. What's your schedule? (I know you have more important things to work on right now).

Thanks
-Robin
