### ISSUE TITLE
"Unable to claim interface"

### ISSUE THREAD

**Issue by cpbridges** [analogdevicesinc/iio-oscilloscope#68]
Hi AD,

I've built and install the ADI IIO Oscilloscope application from git/master on Ubuntu 16.04 but have  an issue in opening the FFT plot. Note that it would appear that RSSI is coming through but parts of the scope are clearly not working. I've screenshotted it below, and how it runs from the terminal.

![screenshot from 2018-02-22 13-43-15](https://user-images.githubusercontent.com/2065141/36541637-784ead4a-17d6-11e8-92d2-c3aa16d3f97e.png)

Any ideas how to get the fft up?

Best, Chris

**Comment by mhennerich** [comment]
File->New Plot ?

**Comment by cpbridges** [comment]
I was totally clicking on the wrong thing in the interface, like an idiot. I think I did the same thing about 10 months ago. Best, Chris
