### ISSUE TITLE
Build information missing

### ISSUE THREAD

**Issue by AtharBaig0027** [analogdevicesinc/iio-oscilloscope#85]
hi, 

I'm looking for build information for iio-oscilloscope and it's plug-ins. I checked the wiki page of this thread but build information is missing. 

Please help me find build information.

**Comment by mhennerich** [comment]
Please see here: https://wiki.analog.com/resources/tools-software/linux-software/iio_oscilloscope

**Comment by mhennerich** [comment]
Fixed with this commit: https://github.com/analogdevicesinc/iio-oscilloscope/commit/c89c6c73a2366d96b9980b44f2c58dcd1c98a25d

Can you try again? what version of GCC are you using?

-Michael

**Comment by AtharBaig0027** [comment]
I removed the unused constant and it built successfully. Thanks. 
I'm using gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0.

**Comment by commodo** [comment]
This looks resolved.
Will close.

If there are still open issues we can re-open or continue here.

Thanks
Alex
