### ISSUE TITLE
fmcomms2 crashes when the capture or transmit device are not present

### ISSUE THREAD

**Issue by lclausen-adi** [analogdevicesinc/iio-oscilloscope#88]
The FMCOMMS2 plugin is supposed to work without the capture and transmit device being present. But currently it crashes in that case.

See https://ez.analog.com/message/355921-re-iio-oscilloscope-segmentation-fault-on-connecting?commentID=355921&et=watches.email.thread#comment-355921

**Comment by dNechita** [comment]
Fixed
