### ISSUE TITLE
loading bad ini crashes

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/iio-oscilloscope#9]
I controlled-C when stopping, and ended up with a malformed ini file.

When I run things again, I get:

ERROR: Unexpected end of line
ERROR: Unexpected end of line
ERROR: Unexpected end of line
ERROR: Unexpected end of line

Program received signal SIGSEGV, Segmentation fault.
0xb6fcc9b6 in update_from_ini_chn_cb (chn=<optimized out>, attr=0x2fbf60 "in_voltage1_hardwaregain", buf=0xb09ff014, len=<optimized out>, d=0xbeffe3bc) at libini2.c:107
107				if (*strstr(tmp, " dB"))
(gdb) bt
#0  0xb6fcc9b6 in update_from_ini_chn_cb (chn=<optimized out>, attr=0x2fbf60 "in_voltage1_hardwaregain", buf=0xb09ff014, len=<optimized out>, d=0xbeffe3bc) at libini2.c:107
#1  0xb6beadc6 in iio_channel_attr_write_all () from /usr/lib/libiio.so.0
#2  0xb6fccb9e in update_from_ini (ini_file=ini_file@entry=0xbeffe8b4 "/root/.osc_profile.ini", driver_name=driver_name@entry=0xb1cf160c "FMComms5", dev=0x2fabd0, 
    whitelist=whitelist@entry=0xb1cfc2a0 <fmcomms5_sr_attribs>, list_len=list_len@entry=128) at libini2.c:142
#3  0xb1cef32e in load_profile (ini_fn=0xbeffe8b4 "/root/.osc_profile.ini") at plugins/fmcomms5.c:1018
#4  0xb6fbcd54 in load_profile (filename=filename@entry=0xbeffe8b4 "/root/.osc_profile.ini", load_plugins=load_plugins@entry=true) at osc.c:1998
#5  0xb6fbcebe in load_profile (filename=0xbeffe8b4 "/root/.osc_profile.ini", load_plugins=<optimized out>) at osc.c:2008
#6  0xb6fbdf10 in load_default_profile (filename=filename@entry=0x0, load_plugins=load_plugins@entry=true) at osc.c:1691
#7  0xb6fbe016 in do_init (new_ctx=0x13db80) at osc.c:1739
#8  0x00009380 in init_application (ini_fn=0x3ff58 "/root/.osc_profile.ini") at oscmain.c:104
#9  main (argc=1, argv=0xbefff2a4) at oscmain.c:183
(gdb) p tmp
$1 = 0xb09ff014 ""
(gdb)  x tmp
0xb09ff014:	0x00000000

I don't think strstr allows an empty haystack, so that needs to be checked before it is deferenced.

-Robin

**Comment by pcercuei** [comment]
Fixed in commit https://github.com/analogdevicesinc/iio-oscilloscope/commit/79e83e6672719576267ed7002d5438b6537b7e38
